all: createshm ctlshm write_attach_shm read_attach_shm t setctlshm fix_addr_shm

createshm:createshm.c
ctlshm:ctlshm.c
write_attach_shm:write_attach_shm.c
read_attach_shm:read_attach_shm.c
t:t.c
setctlshm:setctlshm.c
fix_addr_shm:fix_addr_shm.c
